### ISSUE TITLE
inlinepopup not work when using tabs

### ISSUE THREAD

**Issue by thainguyenit** [Position2/jQuery-Inline-Popup#2]
Hi,
Please help me, inlinepopup not work in tabs when I switch many times
[https://jsfiddle.net/thainguyenit/z51grfxh/8/](url)

**Comment by rhenryrobert** [comment]
Hi @thainguyenit ,

Instead of initiating inlinePopup plugin on each time of tab click. Check a condition whether  inlinePopup plugin is already initiated or not...

**Updated script:**
function girdView(){
  if($(".article[data-row]").length <= 0) {
    $("#ip-container").inlinePopup({
      itemSelector : ".article",
      closeinnerelem: "X"
    })
  }
}

Issue fixed & working demo here : https://jsfiddle.net/6xumg1fw/
